In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
dir(sql)

['Binary',
 'Blob',
 'Connection',
 'Cursor',
 'DataError',
 'DatabaseError',
 'Date',
 'DateFromTicks',
 'Error',
 'IntegrityError',
 'InterfaceError',
 'InternalError',
 'LEGACY_TRANSACTION_CONTROL',
 'NotSupportedError',
 'OperationalError',
 'PARSE_COLNAMES',
 'PARSE_DECLTYPES',
 'PrepareProtocol',
 'ProgrammingError',
 'Row',
 'SQLITE_ABORT',
 'SQLITE_ABORT_ROLLBACK',
 'SQLITE_ALTER_TABLE',
 'SQLITE_ANALYZE',
 'SQLITE_ATTACH',
 'SQLITE_AUTH',
 'SQLITE_AUTH_USER',
 'SQLITE_BUSY',
 'SQLITE_BUSY_RECOVERY',
 'SQLITE_BUSY_SNAPSHOT',
 'SQLITE_BUSY_TIMEOUT',
 'SQLITE_CANTOPEN',
 'SQLITE_CANTOPEN_CONVPATH',
 'SQLITE_CANTOPEN_DIRTYWAL',
 'SQLITE_CANTOPEN_FULLPATH',
 'SQLITE_CANTOPEN_ISDIR',
 'SQLITE_CANTOPEN_NOTEMPDIR',
 'SQLITE_CANTOPEN_SYMLINK',
 'SQLITE_CONSTRAINT',
 'SQLITE_CONSTRAINT_CHECK',
 'SQLITE_CONSTRAINT_COMMITHOOK',
 'SQLITE_CONSTRAINT_FOREIGNKEY',
 'SQLITE_CONSTRAINT_FUNCTION',
 'SQLITE_CONSTRAINT_NOTNULL',
 'SQLITE_CONSTRAINT_PINNED',
 'SQLITE_CONSTRAINT_PRIMARYKEY',
 'SQLITE_CONSTRAINT_ROWID',
 'SQLITE_CONSTRAINT_TRIGGER',
 'SQLITE_CONSTRAINT_UNIQUE',
 'SQLITE_CONSTRAINT_VTAB',
 'SQLITE_CORRUPT',
 'SQLITE_CORRUPT_INDEX',
 'SQLITE_CORRUPT_SEQUENCE',
 'SQLITE_CORRUPT_VTAB',
 'SQLITE_CREATE_INDEX',
 'SQLITE_CREATE_TABLE',
 'SQLITE_CREATE_TEMP_INDEX',
 'SQLITE_CREATE_TEMP_TABLE',
 'SQLITE_CREATE_TEMP_TRIGGER',
 'SQLITE_CREATE_TEMP_VIEW',
 'SQLITE_CREATE_TRIGGER',
 'SQLITE_CREATE_VIEW',
 'SQLITE_CREATE_VTABLE',
 'SQLITE_DBCONFIG_DEFENSIVE',
 'SQLITE_DBCONFIG_DQS_DDL',
 'SQLITE_DBCONFIG_DQS_DML',
 'SQLITE_DBCONFIG_ENABLE_FKEY',
 'SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER',
 'SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION',
 'SQLITE_DBCONFIG_ENABLE_QPSG',
 'SQLITE_DBCONFIG_ENABLE_TRIGGER',
 'SQLITE_DBCONFIG_ENABLE_VIEW',
 'SQLITE_DBCONFIG_LEGACY_ALTER_TABLE',
 'SQLITE_DBCONFIG_LEGACY_FILE_FORMAT',
 'SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE',
 'SQLITE_DBCONFIG_RESET_DATABASE',
 'SQLITE_DBCONFIG_TRIGGER_EQP',
 'SQLITE_DBCONFIG_TRUSTED_SCHEMA',
 'SQLITE_DBCONFIG_WRITABLE_SCHEMA',
 'SQLITE_DELETE',
 'SQLITE_DENY',
 'SQLITE_DETACH',
 'SQLITE_DONE',
 'SQLITE_DROP_INDEX',
 'SQLITE_DROP_TABLE',
 'SQLITE_DROP_TEMP_INDEX',
 'SQLITE_DROP_TEMP_TABLE',
 'SQLITE_DROP_TEMP_TRIGGER',
 'SQLITE_DROP_TEMP_VIEW',
 'SQLITE_DROP_TRIGGER',
 'SQLITE_DROP_VIEW',
 'SQLITE_DROP_VTABLE',
 'SQLITE_EMPTY',
 'SQLITE_ERROR',
 'SQLITE_ERROR_MISSING_COLLSEQ',
 'SQLITE_ERROR_RETRY',
 'SQLITE_ERROR_SNAPSHOT',
 'SQLITE_FORMAT',
 'SQLITE_FULL',
 'SQLITE_FUNCTION',
 'SQLITE_IGNORE',
 'SQLITE_INSERT',
 'SQLITE_INTERNAL',
 'SQLITE_INTERRUPT',
 'SQLITE_IOERR',
 'SQLITE_IOERR_ACCESS',
 'SQLITE_IOERR_AUTH',
 'SQLITE_IOERR_BEGIN_ATOMIC',
 'SQLITE_IOERR_BLOCKED',
 'SQLITE_IOERR_CHECKRESERVEDLOCK',
 'SQLITE_IOERR_CLOSE',
 'SQLITE_IOERR_COMMIT_ATOMIC',
 'SQLITE_IOERR_CONVPATH',
 'SQLITE_IOERR_CORRUPTFS',
 'SQLITE_IOERR_DATA',
 'SQLITE_IOERR_DELETE',
 'SQLITE_IOERR_DELETE_NOENT',
 'SQLITE_IOERR_DIR_CLOSE',
 'SQLITE_IOERR_DIR_FSYNC',
 'SQLITE_IOERR_FSTAT',
 'SQLITE_IOERR_FSYNC',
 'SQLITE_IOERR_GETTEMPPATH',
 'SQLITE_IOERR_LOCK',
 'SQLITE_IOERR_MMAP',
 'SQLITE_IOERR_NOMEM',
 'SQLITE_IOERR_RDLOCK',
 'SQLITE_IOERR_READ',
 'SQLITE_IOERR_ROLLBACK_ATOMIC',
 'SQLITE_IOERR_SEEK',
 'SQLITE_IOERR_SHMLOCK',
 'SQLITE_IOERR_SHMMAP',
 'SQLITE_IOERR_SHMOPEN',
 'SQLITE_IOERR_SHMSIZE',
 'SQLITE_IOERR_SHORT_READ',
 'SQLITE_IOERR_TRUNCATE',
 'SQLITE_IOERR_UNLOCK',
 'SQLITE_IOERR_VNODE',
 'SQLITE_IOERR_WRITE',
 'SQLITE_LIMIT_ATTACHED',
 'SQLITE_LIMIT_COLUMN',
 'SQLITE_LIMIT_COMPOUND_SELECT',
 'SQLITE_LIMIT_EXPR_DEPTH',
 'SQLITE_LIMIT_FUNCTION_ARG',
 'SQLITE_LIMIT_LENGTH',
 'SQLITE_LIMIT_LIKE_PATTERN_LENGTH',
 'SQLITE_LIMIT_SQL_LENGTH',
 'SQLITE_LIMIT_TRIGGER_DEPTH',
 'SQLITE_LIMIT_VARIABLE_NUMBER',
 'SQLITE_LIMIT_VDBE_OP',
 'SQLITE_LIMIT_WORKER_THREADS',
 'SQLITE_LOCKED',
 'SQLITE_LOCKED_SHAREDCACHE',
 'SQLITE_LOCKED_VTAB',
 'SQLITE_MISMATCH',
 'SQLITE_MISUSE',
 'SQLITE_NOLFS',
 'SQLITE_NOMEM',
 'SQLITE_NOTADB',
 'SQLITE_NOTFOUND',
 'SQLITE_NOTICE',
 'SQLITE_NOTICE_RECOVER_ROLLBACK',
 'SQLITE_NOTICE_RECOVER_WAL',
 'SQLITE_OK',
 'SQLITE_OK_LOAD_PERMANENTLY',
 'SQLITE_OK_SYMLINK',
 'SQLITE_PERM',
 'SQLITE_PRAGMA',
 'SQLITE_PROTOCOL',
 'SQLITE_RANGE',
 'SQLITE_READ',
 'SQLITE_READONLY',
 'SQLITE_READONLY_CANTINIT',
 'SQLITE_READONLY_CANTLOCK',
 'SQLITE_READONLY_DBMOVED',
 'SQLITE_READONLY_DIRECTORY',
 'SQLITE_READONLY_RECOVERY',
 'SQLITE_READONLY_ROLLBACK',
 'SQLITE_RECURSIVE',
 'SQLITE_REINDEX',
 'SQLITE_ROW',
 'SQLITE_SAVEPOINT',
 'SQLITE_SCHEMA',
 'SQLITE_SELECT',
 'SQLITE_TOOBIG',
 'SQLITE_TRANSACTION',
 'SQLITE_UPDATE',
 'SQLITE_WARNING',
 'SQLITE_WARNING_AUTOINDEX',
 'Time',
 'TimeFromTicks',
 'Timestamp',
 'TimestampFromTicks',
 'Warning',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_deprecated_names',
 '_deprecated_version',
 '_deprecated_version_info',
 'adapt',
 'adapters',
 'apilevel',
 'collections',
 'complete_statement',
 'connect',
 'converters',
 'datetime',
 'dbapi2',
 'enable_callback_tracebacks',
 'paramstyle',
 'register_adapter',
 'register_converter',
 'sqlite_version',
 'sqlite_version_info',
 'threadsafety',
 'time']

In [3]:
conn = sql.connect('database.sqlite')
conn

In [5]:
'select * from sqllite_master'

'select * from sqllite_master'

In [6]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [7]:
pd.read_sql_query('select * from salaries',conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [8]:
def sql_query(x):
    return pd.read_sql_query(x,conn)

In [10]:
sql_query('select * from salaries')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [12]:
x = 'select * from salaries'
sql_query(x)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [13]:
query = """
SELECT JobTitle, AVG(TotalPayBenefits) AS AverageTotalPayBenefits
FROM Salaries
WHERE JobTitle NOT IN ('Not Provided', 'Not provided')
GROUP BY JobTitle
"""

df = pd.read_sql_query(query, conn)
df

                                            JobTitle  AverageTotalPayBenefits
0                                      ACCOUNT CLERK             44035.664337
1                                         ACCOUNTANT             47429.268000
2                                  ACCOUNTANT INTERN             29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)             80266.370000
4                                      ACUPUNCTURIST             67594.400000
...                                              ...                      ...
2153                           X-RAY LABORATORY AIDE             52705.880385
2154                           X-Ray Laboratory Aide             69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS             53632.870000
2156                              Youth Comm Advisor             60118.550000
2157                                     ZOO CURATOR             66686.560000

[2158 rows x 2 columns]

In [14]:
query = """
SELECT JobTitle, OvertimePay
FROM Salaries
WHERE OvertimePay > 50000
"""

df = pd.read_sql_query(query, conn)
df

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

In [15]:
query = """
SELECT COUNT(DISTINCT EmployeeName) AS UniqueEmployees
FROM Salaries
WHERE EmployeeName NOT IN ('Not Provided', 'Not provided')
"""

df = pd.read_sql_query(query, conn)
df

   UniqueEmployees
0           110808

In [16]:
query = """
SELECT EmployeeName, JobTitle, TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
LIMIT 10
"""

df = pd.read_sql_query(query, conn)
df

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

In [17]:
query = """
SELECT EmployeeName, JobTitle, TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
"""

df = pd.read_sql_query(query, conn)
df

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148648,Not provided,Not provided,0.00
148649,Timothy E Gibson,Police Officer 3,-2.73
148650,Mark E Laherty,Police Officer 3,-8.20
148651,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [18]:
df.head(10)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

In [19]:
df.tail(10)

            EmployeeName                     JobTitle  TotalPayBenefits
148643    Joann Anderson  Communications Dispatcher 2              0.00
148644       Leon Walker                    Custodian              0.00
148645     Roy I Tillery                    Custodian              0.00
148646      Not provided                 Not provided              0.00
148647      Not provided                 Not provided              0.00
148648      Not provided                 Not provided              0.00
148649  Timothy E Gibson             Police Officer 3             -2.73
148650    Mark E Laherty             Police Officer 3             -8.20
148651     David P Kucia             Police Officer 3            -33.89
148652         Joe Lopez   Counselor, Log Cabin Ranch           -618.13

In [20]:
df.describe()

       TotalPayBenefits
count     148653.000000
mean       93689.559804
std        62783.126137
min         -618.130000
25%        44064.410000
50%        92402.210000
75%       132876.300000
max       567595.430000

In [ ]:
df.info()

In [ ]:
df.shape()